---
title: "exploratory_plots"
output: html_document
date: "2023-05-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Objective: The goal of this script is to make some exploratory plots from the data generated from the step 4 in this repo `04_adjusttrade_matrix_pressures_for_feed.Rmd`.

Packages:
```{r}
library(tidyverse)
library(ggplot2)
library(patchwork)
```


## Data Paths
```{r}
trade_path <- "/home/shares/food-systems/social_justice_projects/food_trade_pressures/output_data/04_adjust_trade_matrix_pressures_for_feed/"
```


## Read in data as is
```{r}
trade_data_raw <- read_csv(file.path(trade_path, "trade_matrix_w_pressures_accounting_for_feed.csv"))

list_of_items <- trade_data_raw %>% 
  distinct(item)
```
## Efficiencies explorations
```{r}
pressure_efficiencies <- read.csv("/home/shares/food-systems/social_justice_projects/food_trade_pressures/raw_data/pressures/pressures_efficiencies.csv")
```

## USA Cumulative Pressure
```{r}
USA_cumulative <- trade_data_raw %>% 
  filter(consumer_iso3 == "USA") %>% 
  filter(producer_iso3 != "USA") %>% 
  group_by(producer_iso3, consumer_iso3) %>% 
  summarise(trade_cumu_pressure = sum(trade_cumu_pressure)) %>% 
  ungroup() %>% 
  mutate(percent_total_cumulative = 100*(trade_cumu_pressure/sum(trade_cumu_pressure))) %>% 
  arrange(desc(percent_total_cumulative)) %>% 
  head(n = 20)

ggplot(data = USA_cumulative,
       aes(y = percent_total_cumulative,
           x = reorder(producer_iso3, -percent_total_cumulative))) +
  geom_col(position = "dodge") +
  labs(title = "Percent of Cumulative Pressure Imported to the USA - Top 20 Importers",
       x = "Country ISO3c",
       y = "Percent of Total Cumulative Pressure from Importers") + 
  geom_text(aes(producer_iso3, 
                percent_total_cumulative + 0.5, 
                label =round(percent_total_cumulative, 1)),
            position = position_dodge(0.9),
            vjust = 0)
```

## Barbados Cow Meat Pressures
```{r}
barbados_cow_meat <- trade_data_raw %>% 
  filter(consumer_iso3 == "BRB",
         item == "cows_meat") %>% 
  mutate(percent_total_cumulative = 100*(trade_cumu_pressure/sum(trade_cumu_pressure)),
         percent_total_trade = 100*(tonnes_traded/sum(tonnes_traded))) %>% 
  arrange(desc(percent_total_cumulative)) %>% 
  head(n = 10)

cow_pressure <- ggplot(barbados_cow_meat,
       aes(y = percent_total_cumulative,
           x = reorder(producer_iso3, -percent_total_trade))) +
  geom_col(position = "dodge") +
  labs(title = "Top 10 Contributors to Cumulative Pressure from Cows Meat In Barbardos",
       x = "Country ISO3c",
       y = "Percent of Total Cumulative Pressure of Cows Meat") + 
  geom_text(aes(producer_iso3, 
                percent_total_cumulative + 0.5, 
                label =round(percent_total_cumulative, 1)),
            position = position_dodge(0.9),
            vjust = 0)

cow_trade <- ggplot(barbados_cow_meat,
       aes(y = percent_total_trade,
           x = reorder(producer_iso3, -percent_total_trade))) +
  geom_col(position = "dodge") +
  labs(title = "Top 10 Contributors to Cows Meat Trade in Barbardos",
       x = "Country ISO3c",
       y = "Percent of Cows Meat Trade") + 
  geom_text(aes(producer_iso3, 
                percent_total_trade + 0.5, 
                label =round(percent_total_trade, 1)),
            position = position_dodge(0.9),
            vjust = 0)

cow_pressure/cow_trade

```

## Top 30 Traded items and total traded

```{r}
top_food_pressures <- trade_data_raw %>% 
  filter(producer_iso3 != consumer_iso3) %>% 
  group_by(item) %>% 
  summarise(tonnes_traded = sum(tonnes_traded),
            trade_cumu_pressure = sum(trade_cumu_pressure),
            trade_ghg = sum(trade_ghg),
            trade_water = sum(trade_water),
            trade_disturbance = sum(trade_disturbance),
            trade_nutrient = sum(trade_nutrient)) %>% 
  ungroup() 

top_water_pressures <- top_food_pressures %>% 
  arrange(desc(trade_water)) %>% 
  slice(1:15)

ggplot(top_water_pressures,
       aes(x = tonnes_traded,
           y = trade_water,
           color = item)) +
  geom_point()

top_cumulative_pressures <- top_food_pressures %>% 
  arrange(desc(trade_cumu_pressure)) %>% 
  slice(1:15)

efficient_foods <- top_food_pressures %>% 
  mutate(trade_cumu_pressure = trade_cumu_pressure/tonnes_traded,
         trade_ghg = trade_ghg/tonnes_traded,
         trade_water = trade_water/tonnes_traded,
         trade_disturbance = trade_disturbance/tonnes_traded,
         trade_nutrient = trade_nutrient/tonnes_traded) %>% 
  arrange(trade_cumu_pressure) %>% 
  filter(!str_detect(item, pattern = "palm")) %>% 
  slice(1:15)

ggplot(efficient_foods,
       aes(x = tonnes_traded,
           y = trade_cumu_pressure,
           color = item)) +
  geom_point() +
  labs(title = "The 15 Most Environmentally Efficient Food Items") +
  ylab("Cumulative Pressure Per Tonne Traded") +
  xlab("Total Tonnes Traded")

```

